### ISSUE TITLE
NPE in DroidDetector.getMimeTypeFromResults

### ISSUE THREAD

**Issue by cmacdonald** [openpreserve/nanite#33]
```
java.lang.NullPointerException: null
	at uk.bl.wa.nanite.droid.DroidDetector.getMimeTypeFromResults(DroidDetector.java:443) ~[nanite-core-1.2.0-82.jar:na]
	at uk.bl.wa.nanite.droid.DroidDetector.detect(DroidDetector.java:333) ~[nanite-core-1.2.0-82.jar:na]	
```

Any ideas? It was trying to detect the type of a favicon.ico

Cheers

Craig

**Comment by anjackson** [comment]
Hm, can't reproduce with ICO or PNG favicon files. Do you have an example file I can try?

**Comment by cmacdonald** [comment]
Hi Andy,

A whole lot of RSS feeds also produced this error, e.g. http://www.rcn.com/rcntv/feed/ and http://energy.gov/sites/prod/files/Premise1_2012_GreenButtonData_Texas_0.xml

Cheers,

Craig

**Comment by anjackson** [comment]
I'm not finding any major problems with those examples. I notice you're running an older version (1.2.0-82) - would you mind upgrading to 1.3.1-84 and seeing if the problem persists?

**Comment by anjackson** [comment]
No worries, thanks for letting me know.
